# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sai Kulkarni
full_name: Sai Kulkarni
email: saik2608@gmail.com
email2: saik@uci.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saik.github.io" # the base hostname & protocol for your site
github_username:  saee26
linkedin_username: 
# include: ['_pages']
# footer-links-active:
#   stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
